#include <iostream>
#include "opencv2/opencv.hpp"
  
using namespace cv;  
using namespace std;  

  
int main(int, char**)  
{  
    VideoCapture cap;  
    cap.open("video.flv");  
    //cap.open("test_02.wmv"); 
  
    if( !cap.isOpened() )
    {
        cout << "video didn't open!" << endl;
        return -1;  
    }
  
    Mat frame;  
    Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
    // Mat fgMaskKNN;
    Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
    // Ptr<BackgroundSubtractor> pKNN;
    pMOG2 = createBackgroundSubtractorMOG2(); //MOG2 approach
    // pKNN = createBackgroundSubtractorKNN();

    RNG rng(12345);
    int minBoundingArea = 100;

    for(;;)  
    {  
        double t = (double)cvGetTickCount();  
  
        cap >> frame;  
        if(frame.empty())
        {
            cout << "end of video" << endl;
            break;
        }
        //update the background model
        pMOG2->apply(frame, fgMaskMOG2, 0.1);
        // pKNN->apply(frame, fgMaskKNN, 0.02);
        //get the frame number and write it on the current frame
        stringstream ss;
        rectangle(frame, cv::Point(10, 2), cv::Point(100,20),
                  cv::Scalar(255,255,255), -1);
        ss << cap.get(CAP_PROP_POS_FRAMES);
        string frameNumberString = ss.str();
        putText(frame, frameNumberString.c_str(), cv::Point(15, 15),
                FONT_HERSHEY_SIMPLEX, 0.5 , cv::Scalar(0,0,0));
        //show the current frame and the fg masks
        // imshow("Frame", frame);
        imshow("FG Mask MOG 2", fgMaskMOG2);
        // imshow("FG Mask KNN", fgMaskKNN);

        // show contour rectangles
        vector<vector<Point> > contours;
        vector<Vec4i> hierarchy;
        findContours( fgMaskMOG2, contours, hierarchy, CV_RETR_EXTERNAL, CV_CHAIN_APPROX_SIMPLE, Point(0, 0) );

        for( int i = 0; i< contours.size(); i++ )
        {
            if (contourArea(contours[i]) > minBoundingArea)
            {
                Scalar color = Scalar( rng.uniform(0, 255), rng.uniform(0,255), rng.uniform(0,255) );
                Rect boundRect = boundingRect(contours[i]);
                rectangle( frame, Point(boundRect.x, boundRect.y), Point(boundRect.x + boundRect.width, boundRect.y + boundRect.height), color, 2, 8, 0 );
            }
        }
        imshow( "Contours", frame );

        //get the input from the keyboard
        char keyboard = waitKey( 20 );
  
        
        if(keyboard == 27)
        {
            cout <<"exit" << endl;
            break;
        }

  
        t = (double)cvGetTickCount() - t;  
        cout << "cost time: " << t / ((double)cvGetTickFrequency()*1000.) << endl;  
    }  
    return 0;  
}  
